import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from '@clerk/nextjs';

import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import SidebarComponent from "@/components/shared/SidebarComponent";
import SyncUser from "@/components/shared/SyncUser";
import { getServerUser } from "@/lib/auth";
import Loader from "@/components/shared/Loader";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Logistics Dashboard",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const loadedUser = await getServerUser();

  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >

          <SidebarProvider>
            <SidebarComponent />
            <div className="block md:hidden">
              <SidebarTrigger />
            </div>
            {loadedUser === null ? <Loader/> : <SyncUser />}
            {children}

          </SidebarProvider>

        </body>
      </html>
    </ClerkProvider>
  );
}
